-- TP12C2023 K3521 DATABASERS 7

-- EJECUTAR TODO DESDE ACÁ

USE GD2C2023
GO

-- 1. INICIALIZACIÓN

IF (SCHEMA_ID('DATABASERS') IS NULL)
BEGIN
	EXECUTE('CREATE SCHEMA DATABASERS AUTHORIZATION DBO')
END
ELSE 
	PRINT('EL ESQUEMA "DATABASERS" YA ESTA CREADO')
GO

CREATE PROCEDURE DATABASERS.ELIMINAR_TABLAS_BI
AS
BEGIN
    IF OBJECT_ID('DATABASERS.BI_MONEDA', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_MONEDA;
    IF OBJECT_ID('DATABASERS.BI_TIPO_INMUEBLE', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_TIPO_INMUEBLE;
    IF OBJECT_ID('DATABASERS.BI_RANGO_ETARIO', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_RANGO_ETARIO;
    IF OBJECT_ID('DATABASERS.BI_AMBIENTES_INMUEBLE', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_AMBIENTES_INMUEBLE;
    IF OBJECT_ID('DATABASERS.BI_RANGO_SUPERFICIE', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_RANGO_SUPERFICIE;
    IF OBJECT_ID('DATABASERS.BI_ANUNCIOS', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_ANUNCIOS;
    IF OBJECT_ID('DATABASERS.BI_VENTA', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_VENTA;
    IF OBJECT_ID('DATABASERS.BI_TIEMPO', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_TIEMPO;
    IF OBJECT_ID('DATABASERS.BI_SUCURSAL', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_SUCURSAL;
    IF OBJECT_ID('DATABASERS.BI_ALQUILER', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_ALQUILER;
    IF OBJECT_ID('DATABASERS.BI_ESTADO_ALQUILER', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_ESTADO_ALQUILER;
    IF OBJECT_ID('DATABASERS.BI_PAGO_ALQUILER', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_PAGO_ALQUILER;
    IF OBJECT_ID('DATABASERS.BI_BARRIO', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_BARRIO;
    IF OBJECT_ID('DATABASERS.BI_LOCALIDAD', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_LOCALIDAD;
    IF OBJECT_ID('DATABASERS.BI_TIPO_OPERACION', 'U') IS NOT NULL DROP TABLE DATABASERS.BI_TIPO_OPERACION;
END
GO

EXEC DATABASERS.ELIMINAR_TABLAS_BI

-- 2. CREACION DE TABLAS

-- CREO TABLAS
CREATE PROCEDURE DATABASERS.CREAR_TABLAS_BI
AS
BEGIN

CREATE TABLE DATABASERS.BI_ANUNCIOS(
	BI_ANUNCIOS_SUCURSAL NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_TIPO_OPERACION NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_AMBIENTES_INMUEBLE NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_RANGO_SUPERFICIE INTEGER NOT NULL,
	BI_ANUNCIOS_TIPO_INMUEBLE NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_MONEDA NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_TIEMPO INTEGER NOT NULL,
	BI_ANUNCIOS_RANGO_ETARIO INTEGER NOT NULL,
	BI_ANUNCIOS_BARRIO NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_DIAS_PUBLICADO INTEGER NULL,
	BI_ANUNCIOS_PRECIO_INMUEBLE NUMERIC (18,2) NULL,
	BI_ANUNCIOS_OP_CONTRECTADAS INTEGER NULL,
	BI_ANUNCIOS_MONTO_TOTAL NUMERIC (18,2) NULL,
	BI_ANUNCIOS_COMISION NUMERIC (18,2) NULL,

	PRIMARY KEY(BI_ANUNCIOS_SUCURSAL, BI_ANUNCIOS_TIPO_OPERACION, BI_ANUNCIOS_AMBIENTES_INMUEBLE, BI_ANUNCIOS_RANGO_SUPERFICIE, BI_ANUNCIOS_TIPO_INMUEBLE, 
	BI_ANUNCIOS_MONEDA, BI_ANUNCIOS_TIEMPO, BI_ANUNCIOS_RANGO_ETARIO, BI_ANUNCIOS_BARRIO)

)

CREATE TABLE DATABASERS.BI_RANGO_SUPERFICIE
(
	BI_RANGO_SUPERFICIE_CODIGO INTEGER IDENTITY PRIMARY KEY NOT NULL,
	BI_RANGO_SUPERFICIE_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_RANGO_ETARIO
(
	BI_RANGO_ETARIO_CODIGO INTEGER IDENTITY PRIMARY KEY NOT NULL,
	BI_RANGO_ETARIO_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_AMBIENTES_INMUEBLE
(
	BI_AMBIENTES_INMUEBLE_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_AMBIENTES_INMUEBLE_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_TIPO_OPERACION(
	BI_TIPO_OPERACION_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_TIPO_OPERACION_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_MONEDA
(
	BI_MONEDA_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_MONEDA_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_VENTA
(
	BI_VENTA_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_VENTA_INMUEBLE_SUPERFICIE_TOTAL NUMERIC(18,2) NULL,
	BI_VENTA_LOCALIDAD NUMERIC(18, 0) NULL,
	BI_VENTA_TIEMPO INTEGER NOT NULL,
	BI_VENTA_PRECIO_VENTA NUMERIC(18, 2) NULL,
	BI_VENTA_TIPO_INMUEBLE NUMERIC(18, 0) NOT NULL,
	BI_VENTA_PRECIO_M2 NUMERIC(18, 2) NULL
)

CREATE TABLE DATABASERS.BI_TIPO_INMUEBLE
(
	BI_TIPO_INMUEBLE_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_TIPO_INMUEBLE_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_TIEMPO
(
	BI_TIEMPO_CODIGO INTEGER IDENTITY PRIMARY KEY NOT NULL,
	BI_TIEMPO_ANIO INTEGER NULL,
	BI_TIEMPO_CUATRIMESTRE INTEGER NULL,
	BI_TIEMPO_MES INTEGER NULL,
	BI_TIEMPO_DIA INTEGER NULL
)

CREATE TABLE DATABASERS.BI_SUCURSAL(
	BI_SUCURSAL_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_SUCURSAL_NOMBRE NVARCHAR(100) NULL,
)

CREATE TABLE DATABASERS.BI_ALQUILER
(
	BI_ALQUILER_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_ALQUILER_ANUNCIO NUMERIC(19,0) NULL,
	BI_ALQUILER_ESTADO NUMERIC (18,0) NULL,
	BI_ALQUILER_FECHA_INICIO DATETIME NULL,
	BI_ALQUILER_FECHA_FIN DATETIME NULL,
	BI_ALQUILER_CANT_PERIODOS NUMERIC (18,0) NULL,
	BI_ALQUILER_DEPOSITO NUMERIC (18,2) NULL,
	BI_ALQUILER_COMISION NUMERIC (18,2) NULL,
	BI_ALQUILER_AUMENTO NUMERIC (18,2) NULL,
	BI_ALQUILER_TIEMPO INTEGER NOT NULL,
	BI_ALQUILER_BARRIO NUMERIC(18,0) NULL
	
)

CREATE TABLE DATABASERS.BI_ESTADO_ALQUILER(
	BI_ESTADO_ALQUILER_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_ESTADO_ALQUILER_NOMBRE NVARCHAR (100) NULL
)

CREATE TABLE DATABASERS.BI_PAGO_ALQUILER
(
	BI_PAGO_ALQUILER_CODIGO NUMERIC(18,0) NOT NULL,
	BI_PAGO_ALQUILER_ALQUILER NUMERIC(18,2) NOT NULL,
	BI_PAGO_ALQUILER_NRO_PERIODO NUMERIC(18,0) NULL,
	BI_PAGO_ALQUILER_FECHA DATETIME NULL, 
	BI_PAGO_ALQUILER_IMPORTE NUMERIC (18,2) NULL, 
	BI_PAGO_ALQUILER_FECHA_VENCIMIENTO DATETIME NULL,
	BI_PAGO_ALQUILER_DESC NVARCHAR (100) NULL, 
	BI_PAGO_ALQUILER_FEC_INI DATETIME NULL,
	BI_PAGO_ALQUILER_FEC_FIN DATETIME NULL,
	PRIMARY KEY (BI_PAGO_ALQUILER_CODIGO, BI_PAGO_ALQUILER_ALQUILER)
)

CREATE TABLE DATABASERS.BI_BARRIO (
	BI_BARRIO_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_BARRIO_DETALLE NVARCHAR(100) NULL,
	BI_BARRIO_LOCALIDAD NUMERIC(18,0) NULL
)

CREATE TABLE DATABASERS.BI_LOCALIDAD
(
	BI_LOCALIDAD_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_LOCALIDAD_DETALLE NVARCHAR(100) NULL
)

END
GO

-- 3. ADICIÓN DE FK A LAS TABLAS

CREATE PROCEDURE DATABASERS.AGREGAR_FK_BI
AS
BEGIN

--FK BI_VENTA 
ALTER TABLE DATABASERS.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_LOCALIDAD) REFERENCES DATABASERS.BI_LOCALIDAD(BI_LOCALIDAD_CODIGO);

ALTER TABLE DATABASERS.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_TIEMPO) REFERENCES DATABASERS.BI_TIEMPO(BI_TIEMPO_CODIGO);

ALTER TABLE DATABASERS.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_TIPO_INMUEBLE) REFERENCES DATABASERS.BI_TIPO_INMUEBLE(BI_TIPO_INMUEBLE_CODIGO);

--FK BI_ALQUILER
/*

ALTER TABLE DATABASERS.BI_ALQUILER 
ADD FOREIGN KEY (BI_ALQUILER_BARRIO) REFERENCES DATABASERS.BI_BARRIO(BI_BARRIO_CODIGO); 

ALTER TABLE DATABASERS.BI_ALQUILER 
ADD FOREIGN KEY (BI_ALQUILER_ESTADO) REFERENCES DATABASERS.BI_ESTADO_ALQUILER(BI_ESTADO_ALQUILER_CODIGO);

ALTER TABLE DATABASERS.BI_ALQUILER
ADD FOREIGN KEY (BI_ALQUILER_CODIGO) REFERENCES DATABASERS.BI_PAGO_ALQUILER(BI_PAGO_ALQUILER_CODIGO, BI_PAGO_ALQUILER_ALQUILER); 

*/
--FK BI_ANUNCIO

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_SUCURSAL) REFERENCES DATABASERS.BI_SUCURSAL(BI_SUCURSAL_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_TIPO_OPERACION) REFERENCES DATABASERS.BI_TIPO_OPERACION(BI_TIPO_OPERACION_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_AMBIENTES_INMUEBLE) REFERENCES DATABASERS.BI_AMBIENTES_INMUEBLE(BI_AMBIENTES_INMUEBLE_CODIGO);

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_RANGO_SUPERFICIE) REFERENCES DATABASERS.BI_RANGO_SUPERFICIE(BI_RANGO_SUPERFICIE_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_TIPO_INMUEBLE) REFERENCES DATABASERS.BI_TIPO_INMUEBLE(BI_TIPO_INMUEBLE_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_MONEDA) REFERENCES DATABASERS.BI_MONEDA(BI_MONEDA_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_TIEMPO) REFERENCES DATABASERS.BI_TIEMPO(BI_TIEMPO_CODIGO);

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_RANGO_ETARIO) REFERENCES DATABASERS.BI_RANGO_ETARIO(BI_RANGO_ETARIO_CODIGO);

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_BARRIO) REFERENCES DATABASERS.BI_BARRIO(BI_BARRIO_CODIGO); 

END
GO

-- 4. MIGRACIÓN DE TABLAS

-- PROCEDIMIENTOS

CREATE PROCEDURE DATABASERS.GENERAR_BI_TIEMPO(@fecha datetime, @PK NUMERIC(18,0) OUTPUT)
AS 
BEGIN

	INSERT INTO DATABASERS.BI_TIEMPO 
	(BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE, BI_TIEMPO_MES, BI_TIEMPO_DIA)
	VALUES (YEAR(@FECHA), DATEPART(QUARTER, @FECHA), MONTH(@FECHA), DAY(@FECHA))

	SET @PK = SCOPE_IDENTITY()

END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_RANGO_SUPERFICIE
AS
BEGIN
	INSERT INTO DATABASERS.BI_RANGO_SUPERFICIE (BI_RANGO_SUPERFICIE_DETALLE) VALUES
	('<35'), ('35-55'), ('55-75'), ('75-100'), ('>100')
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_RANGO_ETARIO
AS
BEGIN
	INSERT INTO DATABASERS.BI_RANGO_ETARIO (BI_RANGO_ETARIO_DETALLE) VALUES
	('<25'), ('25-35'), ('35-50'), ('>50')
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_TIPO_INMUEBLE 
AS
BEGIN
	INSERT INTO DATABASERS.BI_TIPO_INMUEBLE (BI_TIPO_INMUEBLE_DETALLE)
	SELECT DISTINCT TIPO_INMUEBLE_DETALLE FROM DATABASERS.TIPO_INMUEBLE
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_TIPO_OPERACION
AS
BEGIN
	INSERT INTO DATABASERS.BI_TIPO_OPERACION (BI_TIPO_OPERACION_DETALLE)
	SELECT DISTINCT TIPO_OPERACION_DETALLE FROM DATABASERS.TIPO_OPERACION
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_MONEDA
AS
BEGIN
	INSERT INTO DATABASERS.BI_MONEDA (BI_MONEDA_DETALLE)
	SELECT DISTINCT MONEDA_DETALLE FROM DATABASERS.MONEDA
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_SUCURSAL
AS
BEGIN
	INSERT INTO DATABASERS.BI_SUCURSAL (BI_SUCURSAL_NOMBRE)
	SELECT DISTINCT SUCURSAL_NOMBRE FROM DATABASERS.SUCURSAL
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_AMBIENTES_INMUEBLE
AS
BEGIN
	INSERT INTO DATABASERS.BI_AMBIENTES_INMUEBLE (BI_AMBIENTES_INMUEBLE_DETALLE)
	SELECT DISTINCT CANT_AMBIENTES_INMUEBLE_DETALLE FROM DATABASERS.CANT_AMBIENTES_INMUEBLE
END
GO


/*
CREATE PROCEDURE DATABASERS.MIGRAR_BI_ESTADO_ALQUILER
AS 
BEGIN 
	INSERT INTO DATABASERS.BI_ESTADO_ALQUILER
	SELECT DISTINCT ESTADO_ALQUILER_CODIGO,ESTADO_ALQUILER_NOMBRE FROM DATABASERS.ESTADO_ALQUILER

END 
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_PAGO_ALQUILER 
AS
BEGIN
	INSERT INTO DATABASERS.BI_PAGO_ALQUILER
	SELECT DISTINCT PAGO_ALQUILER_CODIGO,PAGO_ALQUILER_ALQUILER,PAGO_ALQUILER_NRO_PERIODO,PAGO_ALQUILER_FECHA,PAGO_ALQUILER_IMPORTE,PAGO_ALQUILER_FECHA_VENCIMIENTO,PAGO_ALQUILER_DESC,PAGO_ALQUILER_FEC_INI,PAGO_ALQUILER_FEN_FIN FROM DATABASERS.PAGO_ALQUILER
END
GO */

CREATE PROCEDURE DATABASERS.MIGRAR_BI_BARRIO
AS
BEGIN
	INSERT INTO DATABASERS.BI_BARRIO (BI_BARRIO_DETALLE, BI_BARRIO_LOCALIDAD)
	SELECT DISTINCT BARRIO_DETALLE, BARRIO_LOCALIDAD FROM DATABASERS.BARRIO
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_LOCALIDAD
AS
BEGIN
	INSERT INTO DATABASERS.BI_LOCALIDAD (BI_LOCALIDAD_DETALLE)
	SELECT DISTINCT LOCALIDAD_DETALLE FROM DATABASERS.LOCALIDAD
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_TIEMPO_Y_VENTA
AS
BEGIN
	
	DECLARE @VENTA_CODIGO NUMERIC(18)
	DECLARE @VENTA_ANUNCIO NUMERIC(19)
	DECLARE @VENTA_PRECIO_VENTA NUMERIC(18,2)
	DECLARE @VENTA_FECHA DATETIME

	declare c1 cursor for select VENTA_CODIGO, VENTA_ANUNCIO, VENTA_PRECIO_VENTA, VENTA_FECHA from DATABASERS.VENTA
	open c1
	fetch next from c1 into @VENTA_CODIGO, @VENTA_ANUNCIO,@VENTA_PRECIO_VENTA,@VENTA_FECHA
	while @@FETCH_STATUS = 0
	begin 
			
			DECLARE @FK_BI_TIEMPO NUMERIC(18,0)

			SET @FK_BI_TIEMPO = 0 

			EXEC DATABASERS.GENERAR_BI_TIEMPO @FECHA=@VENTA_FECHA, @PK=@FK_BI_TIEMPO OUTPUT

			INSERT INTO DATABASERS.BI_VENTA
			(BI_VENTA_CODIGO,
			BI_VENTA_INMUEBLE_SUPERFICIE_TOTAL,
			BI_VENTA_LOCALIDAD,
			BI_VENTA_PRECIO_VENTA,
			BI_VENTA_TIPO_INMUEBLE,
			BI_VENTA_PRECIO_M2,
			BI_VENTA_TIEMPO)
			SELECT 
			@VENTA_CODIGO,
			(SELECT INMUEBLE_SUPERFICIETOTAL FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON INMUEBLE_CODIGO = ANUNCIO_INMUEBLE
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			(SELECT SUCURSAL_LOCALIDAD FROM DATABASERS.SUCURSAL
			JOIN DATABASERS.ANUNCIO ON ANUNCIO_SUCURSAL = SUCURSAL_CODIGO
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@VENTA_PRECIO_VENTA,
			(SELECT INMUEBLE_TIPO_INMUEBLE FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON ANUNCIO_INMUEBLE = INMUEBLE_CODIGO
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@VENTA_PRECIO_VENTA /(SELECT INMUEBLE_SUPERFICIETOTAL FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON INMUEBLE_CODIGO = ANUNCIO_INMUEBLE
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@FK_BI_TIEMPO

		fetch next from c1 into @VENTA_CODIGO, @VENTA_ANUNCIO,@VENTA_PRECIO_VENTA,@VENTA_FECHA
	end
	close c1
	deallocate c1

END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_TIEMPO_Y_ALQUILER
AS
BEGIN
	

	DECLARE @ALQUILER_CODIGO NUMERIC(18)
	DECLARE @ALQUILER_FECHA DATETIME

	declare c1 cursor for select ALQUILER_CODIGO, PAGO_ALQUILER_FECHA from DATABASERS.ALQUILER JOIN DATABASERS.PAGO_ALQUILER ON ALQUILER_CODIGO=PAGO_ALQUILER_ALQUILER
	open c1
	fetch next from c1 into @ALQUILER_CODIGO, @ALQUILER_ANUNCIO,@ALQUILER_FECHA
	while @@FETCH_STATUS = 0
	begin 
			
			DECLARE @FK_BI_TIEMPO NUMERIC(18,0)

			SET @FK_BI_TIEMPO = 0 

			EXEC DATABASERS.GENERAR_BI_TIEMPO @FECHA=@ALQUILER_FECHA, @PK=@FK_BI_TIEMPO OUTPUT

			INSERT INTO DATABASERS.BI_ALQUILER
			(BI_ALQUILER_CODIGO,
			BI_ALQUILER_ESTADO,
			BI_ALQUILER_FECHA_INICIO,
			BI_ALQUILER_FECHA_FIN,
			BI_ALQUILER_CANT_PERIODOS,
			BI_ALQUILER_DEPOSITO,
			BI_ALQUILER_COMISION,
			BI_ALQUILER_BARRIO,
			BI_AQLUILER_TIEMPO
			)
			SELECT 
			@ALQUILER_CODIGO,
			(SELECT ALQUILER_ESTADO FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO = @ALQUILER_CODIGO),
			(SELECT ALQUILER_FECHA_INICIO FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO = @ALQUILER_CODIGO),
			(SELECT ALQUILER_FECHA_FIN FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO = @ALQUILER_CODIGO),
			(SELECT ALQUILER_CANT_PERIODOS FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO=@ALQUILER_CODIGO),
			(SELECT ALQUILER_DEPOSITO FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO=@ALQUILER_CODIGO),
			(SELECT ALQUILER_COMISION FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO=@ALQUILER_CODIGO),			
			@FK_BI_TIEMPO

		fetch next from c1 into @ALQUILER_CODIGO,@ALQUILER_FECHA
	end
	close c1
	deallocate c1



END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_RELACIONAL
AS
BEGIN
	EXECUTE DATABASERS.MIGRAR_BI_RANGO_SUPERFICIE
	EXECUTE DATABASERS.MIGRAR_BI_RANGO_ETARIO
	EXECUTE DATABASERS.MIGRAR_BI_TIPO_INMUEBLE
	EXECUTE DATABASERS.MIGRAR_BI_TIPO_OPERACION
	EXECUTE DATABASERS.MIGRAR_BI_MONEDA
	EXECUTE DATABASERS.MIGRAR_BI_SUCURSAL
	EXECUTE DATABASERS.MIGRAR_BI_AMBIENTES_INMUEBLE
	--EXECUTE DATABASERS.MIGRAR_BI_ESTADO_ALQUILER
	--EXECUTE DATABASERS.MIGRAR_BI_PAGO_ALQUILER
	EXECUTE DATABASERS.MIGRAR_BI_BARRIO
	EXECUTE DATABASERS.MIGRAR_BI_LOCALIDAD
	EXECUTE DATABASERS.MIGRAR_BI_TIEMPO_Y_VENTA

END
GO

EXEC DATABASERS.MIGRAR_RELACIONAL



--VISTAS

CREATE VIEW DATABASERS.PRECIO_PROM_M2_VENTAS
AS
SELECT BI_TIPO_INMUEBLE_DETALLE, BI_LOCALIDAD_DETALLE, BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE, AVG(BI_VENTA_PRECIO_M2) AS PROM_PRECIO_M2
FROM DATABASERS.BI_VENTA 
JOIN DATABASERS.BI_TIPO_INMUEBLE ON BI_VENTA_TIPO_INMUEBLE= BI_TIPO_INMUEBLE_CODIGO
JOIN DATABASERS.BI_LOCALIDAD ON BI_VENTA_LOCALIDAD = BI_LOCALIDAD_CODIGO
JOIN DATABASERS.BI_TIEMPO ON BI_VENTA_TIEMPO = BI_TIEMPO_CODIGO
GROUP BY  BI_TIPO_INMUEBLE_DETALLE, BI_LOCALIDAD_DETALLE, BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE

CREATE VIEW DATABASERS.PORCENTAJE_INCUMPLIMIENTO
AS
SELECT (100*(SELECT COUNT(DISTINCT P2.PAGO_ALQUILER_CODIGO) FROM DATABASERS.BI_ALQUILER A2
JOIN DATABASERS.BI_PAGO_ALQUILER P2 ON P2.BI_PAGO_ALQUILER_ALQUILER=A2.BI_ALQUILER_CODIGO
JOIN DATABASERS.BI_TIEMPO T2 ON T2.BI_TIEMPO_CODIGO=A2.ALQUILER_TIEMPO
WHERE P2.PAGO_ALQUILER_FECHA_VENCIMIENTO>P2.PAGO_ALQUILER_FECHA and T2.BI_TIEMPO_ANIO=T1.BI_TIEMPO_ANIO and T2.BI_TIEMPO_MES=T1.BI_TIEMPO_MES
GROUP BY T2.BI_TIEMPO_ANIO,T2.BI_TIEMPO_MES))/COUNT(P1.PAGO_ALQUILER_CODIGO) FROM DATABASERS.BI_ALQUILER A1
JOIN DATABASERS.BI_PAGO_ALQUILER P1 ON A1.BI_ALQUILER_CODIGO=P1.BI_PAGO_ALQUILER_ALQUILER 
JOIN DATABASERS.BI_TIEMPO T1 ON T1.BI_TIEMPO_CODIGO=A1.BI_ALQUILER_TIEMPO
GROUP BY T1.BI_TIEMPO_ANIO,T1.BI_TIEMPO_MES

CREATE VIEW DATABASERS.INCREMENTO_ALQUILER
AS
SELECT (100*(P1.BI_PAGO_ALQUILER_IMPORTE-(SELECT P2.BI_PAGO_ALQUILER_IMPORTE FROM DATABASERS.BI_ALQUILER A2
JOIN DATABASERS.BI_PAGO_ALQUILER P2 ON P2.BI_PAGO_ALQUILER_ALQUILER=A2.BI_ALQUILER_CODIGO 
JOIN DATABASERS.BI_TIEMPO T2 ON T2.BI_TIEMPO_CODIGO=A2.ALQUILER_TIEMPO
WHERE T2.BI_TIEMPO_MES=T1.BI_TIEMPO_MES-1)))/(SELECT P2.BI_PAGO_ALQUILER_IMPORTE FROM DATABASERS.BI_ALQUILER A2
JOIN DATABASERS.BI_PAGO_ALQUILER P2 ON P2.BI_PAGO_ALQUILER_ALQUILER=A2.BI_ALQUILER_CODIGO 
JOIN DATABASERS.BI_TIEMPO T2 ON T2.BI_TIEMPO_CODIGO=A2.ALQUILER_TIEMPO
WHERE T2.BI_TIEMPO_MES=T1.BI_TIEMPO_MES-1) FROM DATABASERS.BI_ALQUILER A1 JOIN DATABASERS.BI_ESTADO_ALQUILER E1 ON E1.BI_ESTADO_ALQUILER_CODIGO=A1.BI_ALQUILER_ESTADO 
JOIN DATABASERS.BI_PAGO_ALQUILER P1 ON P1.BI_PAGO_ALQUILER_ALQUILER=A1.BI_ALQUILER_CODIGO
JOIN DATABASERS.BI_TIEMPO T1 ON T1.BI_TIEMPO_CODIGO=A1.BI_ALQUILER_TIEMPO
WHERE P1.BI_PAGO_ALQUILER_IMPORTE> (SELECT P3.BI_PAGO_ALQUILER_IMPORTE FROM DATABASERS.BI_ALQUILER A3
JOIN DATABASERS.BI_PAGO_ALQUILER P3 ON P3.BI_PAGO_ALQUILER_ALQUILER=A3.BI_ALQUILER_CODIGO 
JOIN DATABASERS.BI_TIEMPO T3 ON T3.BI_TIEMPO_CODIGO=A3.ALQUILER_TIEMPO
WHERE T3.BI_TIEMPO_MES=T1.BI_TIEMPO_MES-1)
GROUP BY T1.BI_TIEMPO_MES
--SELECCION VISTA

SELECT * FROM  DATABASERS.PRECIO_PROM_M2_VENTAS