-- TP12C2023 K3521 DATABASERS 7

-- EJECUTAR TODO DESDE ACÁ

USE GD2C2023
GO

IF (SCHEMA_ID('DATABASERS_BI') IS NULL)
BEGIN
	EXECUTE('CREATE SCHEMA DATABASERS_BI AUTHORIZATION DBO')
END
ELSE 
	PRINT('EL ESQUEMA "DATABASERS_BI" YA ESTA CREADO')
GO


--TABLAS

CREATE PROCEDURE DATABASERS_BI.CREAR_TABLAS
AS
BEGIN
CREATE TABLE DATABASERS_BI.BI_VENTA
(
	BI_VENTA_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_VENTA_INMUEBLE_SUPERFICIE_TOTAL NUMERIC(18,2) NULL,
	BI_VENTA_LOCALIDAD NUMERIC(18, 0) NULL,
	BI_VENTA_TIEMPO INTEGER NOT NULL,
	BI_VENTA_PRECIO_VENTA NUMERIC(18, 2) NULL,
	BI_VENTA_TIPO_INMUEBLE NUMERIC(18, 0) NOT NULL,
	BI_VENTA_PRECIO_M2 NUMERIC(18, 2) NULL
)

CREATE TABLE DATABASERS_BI.BI_LOCALIDAD
(
	BI_LOCALIDAD_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_LOCALIDAD_DETALLE NVARCHAR(100) NULL
)


CREATE TABLE DATABASERS_BI.BI_TIPO_INMUEBLE
(
	BI_TIPO_INMUEBLE_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_TIPO_INMUEBLE_DETALLE NVARCHAR(100) NULL
)



CREATE TABLE DATABASERS_BI.BI_TIEMPO
(
	BI_TIEMPO_CODIGO INTEGER IDENTITY PRIMARY KEY NOT NULL,
	BI_TIEMPO_ANIO INTEGER NULL,
	BI_TIEMPO_CUATRIMESTRE INTEGER NULL,
	BI_TIEMPO_MES INTEGER NULL,
	BI_TIEMPO_DIA INTEGER NULL
)

CREATE TABLE DATABASERS_BI.BI_ALQUILER
(
	BI_ALQUILER_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_ALQUILER_ANUNCIO NUMERIC(19,0) NULL,
	BI_ALQUILER_ESTADO NUMERIC (18,0) NULL,
	BI_ALQUILER_FECHA_INICIO DATETIME NULL,
	BI_ALQUILER_FECHA_FIN DATETIME NULL,
	BI_ALQUILER_CANT_PERIODOS NUMERIC (18,0) NULL,
	BI_ALQUILER_DEPOSITO NUMERIC (18,2) NULL,
	BI_ALQUILER_COMISION NUMERIC (18,2) NULL,
	BI_ALQUILER_AUMENTO NUMERIC (18,2) NULL,
	BI_ALQUILER_TIEMPO INTEGER NOT NULL,
	BI_ALQUILER_BARRIO NUMERIC(18,0) NULL
	
)

CREATE TABLE DATABASERS_BI.BI_ESTADO_ALQUILER(
	BI_ESTADO_ALQUILER_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_ESTADO_ALQUILER_NOMBRE NVARCHAR (100) NULL

)

CREATE TABLE DATABASERS_BI.BI_PAGO_ALQUILER
(
	BI_PAGO_ALQUILER_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_PAGO_ALQUILER_ALQUILER NUMERIC(18,2) PRIMARY KEY NULL,
	BI_PAGO_ALQUILER_NRO_PERIODO NUMERIC(18,0) NULL,
	BI_PAGO_ALQUILER_FECHA DATETIME NULL, 
	BI_PAGO_ALQUILER_IMPORTE NUMERIC (18,2) NULL, 
	BI_PAGO_ALQUILER_FECHA_VENCIMIENTO DATETIME NULL,
	BI_PAGO_ALQUILER_DESC NVARCHAR (100) NULL, 
	BI_PAGO_ALQUILER_FEC_INI DATETIME NULL,
	BI_PAGO_ALQUILER_FEC_FIN DATETIME NULL 

)

CREATE TABLE DATABASERS_BI.BI_BARRIO (
	BI_BARRIO_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_BARRIO_DETALLE NVARCHAR(100) NULL,
	BI_BARRIO_LOCALIDAD NUMERIC(18,0) NULL
) 

END


--FK

CREATE PROCEDURE DATABASERS_BI.AGREGAR_FK
AS
BEGIN

--FK BI_VENTA 
ALTER TABLE DATABASERS_BI.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_LOCALIDAD) REFERENCES DATABASERS_BI.BI_LOCALIDAD(BI_LOCALIDAD_CODIGO);

ALTER TABLE DATABASERS_BI.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_TIEMPO) REFERENCES DATABASERS_BI.BI_TIEMPO(BI_TIEMPO_CODIGO);

ALTER TABLE DATABASERS_BI.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_TIPO_INMUEBLE) REFERENCES DATABASERS_BI.BI_TIPO_INMUEBLE(BI_TIPO_INMUEBLE_CODIGO);

--FK BI_ALQUILER

ALTER TABLE DATABASERS_BI.BI_ALQUILER 
ADD FOREIGN KEY (BI_ALQUILER_BARRIO) REFERENCES DATABASERS_BI.BI_BARRIO(BI_BARRIO_CODIGO); 

ALTER TABLE DATABASERS_BI.BI_ALQUILER 
ADD FOREIGN KEY (BI_ALQUILER_ESTADO) REFERENCES DATABASERS_BI.BI_ESTADO_ALQUILER(BI_ESTADO_ALQUILER_CODIGO);

ALTER TABLE DATABASERS_BI.BI_ALQUILER
ADD FOREIGN KEY (BI_ALQUILER_CODIGO) REFERENCES DATABASERS_BI.BI_PAGO_ALQUILER(BI_PAGO_ALQUILER_ALQUILER); 



END



-- MIGRACIÓN DE TABLAS

-- PROCEDIMIENTOS

CREATE PROCEDURE DATABASERS_BI.MIGRAR_BI_ESTADO_ALQUILER
AS 
BEGIN 
	INSERT INTO DATABASERS_BI.BI_ESTADO_ALQUILER
	SELECT DISTINCT ESTADO_ALQUILER_CODIGO,ESTADO_ALQUILER_NOMBRE FROM DATABASERS.ESTADO_ALQUILER

END 
GO

CREATE PROCEDURE DATABASERS_BI.MIGRAR_BI_PAGO_ALQUILER 
AS
BEGIN
	INSERT INTO DATABASERS_BI.BI_PAGO_ALQUILER
	SELECT DISTINCT PAGO_ALQUILER_CODIGO,PAGO_ALQUILER_ALQUILER,PAGO_ALQUILER_NRO_PERIODO,PAGO_ALQUILER_FECHA,PAGO_ALQUILER_IMPORTE,PAGO_ALQUILER_FECHA_VENCIMIENTO,PAGO_ALQUILER_DESC,PAGO_ALQUILER_FEC_INI,PAGO_ALQUILER_FEN_FIN FROM DATABASERS.PAGO_ALQUILER
END
GO

CREATE PROCEDURE DATABASERS_BI.MIGRAR_BI_BARRIO
AS
BEGIN
	INSERT INTO DATABASERS_BI.BI_BARRIO
	SELECT DISTINCT BARRIO_CODIGO,BARRIO_DETALLE,BARRIO_LOCALIDAD FROM DATABASERS.BARRIO
END
GO

CREATE PROCEDURE DATABASERS_BI.MIGRAR_BI_TIPO_INMUEBLE 
AS
BEGIN
	INSERT INTO DATABASERS_BI.BI_TIPO_INMUEBLE
	SELECT DISTINCT TIPO_INMUEBLE_CODIGO, TIPO_INMUEBLE_DETALLE FROM DATABASERS.TIPO_INMUEBLE
END
GO

CREATE PROCEDURE DATABASERS_BI.MIGRAR_BI_LOCALIDAD
AS
BEGIN
	INSERT INTO DATABASERS_BI.BI_LOCALIDAD
	SELECT DISTINCT LOCALIDAD_CODIGO, LOCALIDAD_DETALLE FROM DATABASERS.LOCALIDAD
END
GO


CREATE PROCEDURE DATABASERS_BI.GENERAR_BI_TIEMPO(@fecha datetime, @PK NUMERIC(18,0) OUTPUT)
AS 
BEGIN

	INSERT INTO DATABASERS_BI.BI_TIEMPO 
	(BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE, BI_TIEMPO_MES, BI_TIEMPO_DIA)
	VALUES (YEAR(@FECHA), DATEPART(QUARTER, @FECHA), MONTH(@FECHA), DAY(@FECHA))

	SET @PK = SCOPE_IDENTITY()

END

CREATE PROCEDURE DATABASERS_BI.MIGRAR_BI_TIEMPO_Y_VENTA
AS
BEGIN
	

	DECLARE @VENTA_CODIGO NUMERIC(18)
	DECLARE @VENTA_ANUNCIO NUMERIC(19)
	DECLARE @VENTA_PRECIO_VENTA NUMERIC(18,2)
	DECLARE @VENTA_FECHA DATETIME

	declare c1 cursor for select VENTA_CODIGO, VENTA_ANUNCIO, VENTA_PRECIO_VENTA, VENTA_FECHA from DATABASERS.VENTA
	open c1
	fetch next from c1 into @VENTA_CODIGO, @VENTA_ANUNCIO,@VENTA_PRECIO_VENTA,@VENTA_FECHA
	while @@FETCH_STATUS = 0
	begin 
			
			DECLARE @FK_BI_TIEMPO NUMERIC(18,0)

			SET @FK_BI_TIEMPO = 0 

			EXEC DATABASERS_BI.GENERAR_BI_TIEMPO @FECHA=@VENTA_FECHA, @PK=@FK_BI_TIEMPO OUTPUT

			INSERT INTO DATABASERS_BI.BI_VENTA
			(BI_VENTA_CODIGO,
			BI_VENTA_INMUEBLE_SUPERFICIE_TOTAL,
			BI_VENTA_LOCALIDAD,
			BI_VENTA_PRECIO_VENTA,
			BI_VENTA_TIPO_INMUEBLE,
			BI_VENTA_PRECIO_M2,
			BI_VENTA_TIEMPO)
			SELECT 
			@VENTA_CODIGO,
			(SELECT INMUEBLE_SUPERFICIETOTAL FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON INMUEBLE_CODIGO = ANUNCIO_INMUEBLE
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			(SELECT SUCURSAL_LOCALIDAD FROM DATABASERS.SUCURSAL
			JOIN DATABASERS.ANUNCIO ON ANUNCIO_SUCURSAL = SUCURSAL_CODIGO
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@VENTA_PRECIO_VENTA,
			(SELECT INMUEBLE_TIPO_INMUEBLE FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON ANUNCIO_INMUEBLE = INMUEBLE_CODIGO
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@VENTA_PRECIO_VENTA /(SELECT INMUEBLE_SUPERFICIETOTAL FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON INMUEBLE_CODIGO = ANUNCIO_INMUEBLE
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@FK_BI_TIEMPO

		fetch next from c1 into @VENTA_CODIGO, @VENTA_ANUNCIO,@VENTA_PRECIO_VENTA,@VENTA_FECHA
	end
	close c1
	deallocate c1



END
GO

CREATE PROCEDURE DATABASERS_BI.MIGRAR_BI_TIEMPO_Y_ALQUILER
AS
BEGIN
	

	DECLARE @ALQUILER_CODIGO NUMERIC(18)
	DECLARE @ALQUILER_FECHA DATETIME

	declare c1 cursor for select ALQUILER_CODIGO, PAGO_ALQUILER_FECHA from DATABASERS.ALQUILER JOIN DATABASERS.PAGO_ALQUILER ON ALQUILER_CODIGO=PAGO_ALQUILER_ALQUILER
	open c1
	fetch next from c1 into @ALQUILER_CODIGO, @ALQUILER_ANUNCIO,@ALQUILER_FECHA
	while @@FETCH_STATUS = 0
	begin 
			
			DECLARE @FK_BI_TIEMPO NUMERIC(18,0)

			SET @FK_BI_TIEMPO = 0 

			EXEC DATABASERS_BI.GENERAR_BI_TIEMPO @FECHA=@ALQUILER_FECHA, @PK=@FK_BI_TIEMPO OUTPUT

			INSERT INTO DATABASERS_BI.BI_ALQUILER
			(BI_ALQUILER_CODIGO,
			BI_ALQUILER_ESTADO,
			BI_ALQUILER_FECHA_INICIO,
			BI_ALQUILER_FECHA_FIN,
			BI_ALQUILER_CANT_PERIODOS,
			BI_ALQUILER_DEPOSITO,
			BI_ALQUILER_COMISION,
			BI_ALQUILER_BARRIO,
			BI_AQLUILER_TIEMPO
			)
			SELECT 
			@ALQUILER_CODIGO,
			(SELECT ALQUILER_ESTADO FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO = @ALQUILER_CODIGO),
			(SELECT ALQUILER_FECHA_INICIO FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO = @ALQUILER_CODIGO),
			(SELECT ALQUILER_FECHA_FIN FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO = @ALQUILER_CODIGO),
			(SELECT ALQUILER_CANT_PERIODOS FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO=@ALQUILER_CODIGO),
			(SELECT ALQUILER_DEPOSITO FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO=@ALQUILER_CODIGO),
			(SELECT ALQUILER_COMISION FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO=@ALQUILER_CODIGO),			
			@FK_BI_TIEMPO

		fetch next from c1 into @ALQUILER_CODIGO,@ALQUILER_FECHA
	end
	close c1
	deallocate c1



END
GO


--VISTAS

CREATE VIEW DATABASERS_BI.PRECIO_PROM_M2_VENTAS
AS
SELECT BI_TIPO_INMUEBLE_DETALLE, BI_LOCALIDAD_DETALLE, BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE, AVG(BI_VENTA_PRECIO_M2) AS PROM_PRECIO_M2
FROM DATABASERS_BI.BI_VENTA 
JOIN DATABASERS_BI.BI_TIPO_INMUEBLE ON BI_VENTA_TIPO_INMUEBLE= BI_TIPO_INMUEBLE_CODIGO
JOIN DATABASERS_BI.BI_LOCALIDAD ON BI_VENTA_LOCALIDAD = BI_LOCALIDAD_CODIGO
JOIN DATABASERS_BI.BI_TIEMPO ON BI_VENTA_TIEMPO = BI_TIEMPO_CODIGO
GROUP BY  BI_TIPO_INMUEBLE_DETALLE, BI_LOCALIDAD_DETALLE, BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE

CREATE VIEW DATABASERS_BI.PORCENTAJE_INCUMPLIMIENTO
AS
SELECT (100*(SELECT COUNT(DISTINCT P2.PAGO_ALQUILER_CODIGO) FROM DATABASERS_BI.BI_ALQUILER A2
JOIN DATABASERS_BI.BI_PAGO_ALQUILER P2 ON P2.BI_PAGO_ALQUILER_ALQUILER=A2.BI_ALQUILER_CODIGO
JOIN DATABASERS_BI.BI_TIEMPO T2 ON T2.BI_TIEMPO_CODIGO=A2.ALQUILER_CODIGO
WHERE P2.PAGO_ALQUILER_FECHA_VENCIMIENTO>P2.PAGO_ALQUILER_FECHA
GROUP BY T1.BI_TIEMPO_ANIO,T1.BI_TIEMPO_MES))/COUNT(P1.PAGO_ALQUILER_CODIGO) FROM DATABASERS_BI.BI_ALQUILER A1
JOIN DATABASERS_BI.BI_PAGO_ALQUILER P1 ON A1.BI_ALQUILER_CODIGO=P1.BI_PAGO_ALQUILER_ALQUILER 
JOIN DATABASERS_BI.BI_TIEMPO T1 ON T1.BI_TIEMPO_CODIGO=A1.BI_ALQUILER_TIEMPO
GROUP BY T1.BI_TIEMPO_ANIO,T1.BI_TIEMPO_MES

--SELECCION VISTA

SELECT * FROM  DATABASERS_BI.PRECIO_PROM_M2_VENTAS