-- TP12C2023 K3521 DATABASERS 7

-- EJECUTAR TODO DESDE ACÁ

USE GD2C2023
GO

-- 1. INICIALIZACIÓN

IF (SCHEMA_ID('DATABASERS') IS NULL)
BEGIN
	EXECUTE('CREATE SCHEMA DATABASERS AUTHORIZATION DBO')
END
ELSE 
	PRINT('EL ESQUEMA "DATABASERS" YA ESTA CREADO')
GO


-- 2. CREACION DE TABLAS

-- CREO TABLAS
CREATE PROCEDURE DATABASERS.CREAR_TABLAS_BI
AS
BEGIN

CREATE TABLE DATABASERS.BI_ANUNCIOS(
	BI_ANUNCIOS_SUCURSAL NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_TIPO_OPERACION NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_AMBIENTES_INMUEBLE NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_RANGO_SUPERFICIE INTEGER NOT NULL,
	BI_ANUNCIOS_TIPO_INMUEBLE NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_MONEDA NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_TIEMPO INTEGER NOT NULL,
	BI_ANUNCIOS_RANGO_ETARIO INTEGER NOT NULL,
	BI_ANUNCIOS_BARRIO NUMERIC (18,0) NOT NULL,
	BI_ANUNCIOS_DIAS_PUBLICADO INTEGER NULL,
	BI_ANUNCIOS_PRECIO_INMUEBLE NUMERIC (18,2) NULL,
	BI_ANUNCIOS_OP_CONTRECTADAS INTEGER NULL,
	BI_ANUNCIOS_MONTO_TOTAL NUMERIC (18,2) NULL,
	BI_ANUNCIOS_COMISION NUMERIC (18,2) NULL,

	PRIMARY KEY(BI_ANUNCIOS_SUCURSAL, BI_ANUNCIOS_TIPO_OPERACION, BI_ANUNCIOS_AMBIENTES_INMUEBLE, BI_ANUNCIOS_RANGO_SUPERFICIE, BI_ANUNCIOS_TIPO_INMUEBLE, 
	BI_ANUNCIOS_MONEDA, BI_ANUNCIOS_TIEMPO, BI_ANUNCIOS_RANGO_ETARIO, BI_ANUNCIOS_BARRIO)

)

CREATE TABLE DATABASERS.BI_RANGO_SUPERFICIE
(
	BI_RANGO_SUPERFICIE_CODIGO INTEGER IDENTITY PRIMARY KEY NOT NULL,
	BI_RANGO_SUPERFICIE_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_RANGO_ETARIO
(
	BI_RANGO_ETARIO_CODIGO INTEGER IDENTITY PRIMARY KEY NOT NULL,
	BI_RANGO_ETARIO_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_AMBIENTES_INMUEBLE
(
	BI_AMBIENTES_INMUEBLE_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_AMBIENTES_INMUEBLE_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_TIPO_OPERACION(
	BI_TIPO_OPERACION_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_TIPO_OPERACION_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_MONEDA
(
	BI_MONEDA_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_MONEDA_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_VENTA
(
	BI_VENTA_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_VENTA_INMUEBLE_SUPERFICIE_TOTAL NUMERIC(18,2) NULL,
	BI_VENTA_LOCALIDAD NUMERIC(18, 0) NULL,
	BI_VENTA_TIEMPO INTEGER NOT NULL,
	BI_VENTA_PRECIO_VENTA NUMERIC(18, 2) NULL,
	BI_VENTA_TIPO_INMUEBLE NUMERIC(18, 0) NOT NULL,
	BI_VENTA_PRECIO_M2 NUMERIC(18, 2) NULL
)

CREATE TABLE DATABASERS.BI_TIPO_INMUEBLE
(
	BI_TIPO_INMUEBLE_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_TIPO_INMUEBLE_DETALLE NVARCHAR(100) NULL
)

CREATE TABLE DATABASERS.BI_TIEMPO
(
	BI_TIEMPO_CODIGO INTEGER IDENTITY PRIMARY KEY NOT NULL,
	BI_TIEMPO_ANIO INTEGER NULL,
	BI_TIEMPO_CUATRIMESTRE INTEGER NULL,
	BI_TIEMPO_MES INTEGER NULL,
	BI_TIEMPO_DIA INTEGER NULL
)

CREATE TABLE DATABASERS.BI_SUCURSAL(
	BI_SUCURSAL_CODIGO NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	BI_SUCURSAL_NOMBRE NVARCHAR(100) NULL,
)

CREATE TABLE DATABASERS.BI_ALQUILER
(
	BI_ALQUILER_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_ALQUILER_ESTADO NUMERIC (18,0) NULL,
	BI_ALQUILER_BARRIO NUMERIC(18,0) NULL,
	BI_ALQUILER_PAGO NUMERIC(18,2),
	BI_ALQUILER_ATRASO_PAGO NUMERIC (18,2) NULL,
	BI_ALQUILER_TIEMPO INTEGER NOT NULL,

	
)

CREATE TABLE DATABASERS.BI_ESTADO_ALQUILER(
	BI_ESTADO_ALQUILER_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_ESTADO_ALQUILER_NOMBRE NVARCHAR (100) NULL
)


CREATE TABLE DATABASERS.BI_BARRIO (
	BI_BARRIO_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_BARRIO_DETALLE NVARCHAR(100) NULL,
	BI_BARRIO_LOCALIDAD NUMERIC(18,0) NULL
)

CREATE TABLE DATABASERS.BI_LOCALIDAD
(
	BI_LOCALIDAD_CODIGO NUMERIC(18,0) PRIMARY KEY NOT NULL,
	BI_LOCALIDAD_DETALLE NVARCHAR(100) NULL
)

END
GO

-- 3. ADICIÓN DE FK A LAS TABLAS

CREATE PROCEDURE DATABASERS.AGREGAR_FK_BI
AS
BEGIN

--FK BI_VENTA 
ALTER TABLE DATABASERS.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_LOCALIDAD) REFERENCES DATABASERS.BI_LOCALIDAD(BI_LOCALIDAD_CODIGO);

ALTER TABLE DATABASERS.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_TIEMPO) REFERENCES DATABASERS.BI_TIEMPO(BI_TIEMPO_CODIGO);

ALTER TABLE DATABASERS.BI_VENTA
ADD FOREIGN KEY (BI_VENTA_TIPO_INMUEBLE) REFERENCES DATABASERS.BI_TIPO_INMUEBLE(BI_TIPO_INMUEBLE_CODIGO);

--FK BI_ALQUILER
/*

ALTER TABLE DATABASERS.BI_ALQUILER 
ADD FOREIGN KEY (BI_ALQUILER_BARRIO) REFERENCES DATABASERS.BI_BARRIO(BI_BARRIO_CODIGO); 

ALTER TABLE DATABASERS.BI_ALQUILER 
ADD FOREIGN KEY (BI_ALQUILER_ESTADO) REFERENCES DATABASERS.BI_ESTADO_ALQUILER(BI_ESTADO_ALQUILER_CODIGO);

ALTER TABLE DATABASERS.BI_ALQUILER
ADD FOREIGN KEY (BI_ALQUILER_CODIGO) REFERENCES DATABASERS.BI_PAGO_ALQUILER(BI_PAGO_ALQUILER_CODIGO, BI_PAGO_ALQUILER_ALQUILER); 

*/
--FK BI_ANUNCIO

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_SUCURSAL) REFERENCES DATABASERS.BI_SUCURSAL(BI_SUCURSAL_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_TIPO_OPERACION) REFERENCES DATABASERS.BI_TIPO_OPERACION(BI_TIPO_OPERACION_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_AMBIENTES_INMUEBLE) REFERENCES DATABASERS.BI_AMBIENTES_INMUEBLE(BI_AMBIENTES_INMUEBLE_CODIGO);

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_RANGO_SUPERFICIE) REFERENCES DATABASERS.BI_RANGO_SUPERFICIE(BI_RANGO_SUPERFICIE_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_TIPO_INMUEBLE) REFERENCES DATABASERS.BI_TIPO_INMUEBLE(BI_TIPO_INMUEBLE_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_MONEDA) REFERENCES DATABASERS.BI_MONEDA(BI_MONEDA_CODIGO); 

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_TIEMPO) REFERENCES DATABASERS.BI_TIEMPO(BI_TIEMPO_CODIGO);

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_RANGO_ETARIO) REFERENCES DATABASERS.BI_RANGO_ETARIO(BI_RANGO_ETARIO_CODIGO);

ALTER TABLE DATABASERS.BI_ANUNCIOS
ADD FOREIGN KEY (BI_ANUNCIOS_BARRIO) REFERENCES DATABASERS.BI_BARRIO(BI_BARRIO_CODIGO); 

END
GO

-- 4. MIGRACIÓN DE TABLAS

-- PROCEDIMIENTOS

CREATE PROCEDURE DATABASERS.MIGRAR_BI_ESTADO_ALQUILER
AS 
BEGIN 
	INSERT INTO DATABASERS.BI_ESTADO_ALQUILER
	SELECT DISTINCT ESTADO_ALQUILER_CODIGO,ESTADO_ALQUILER_NOMBRE FROM DATABASERS.ESTADO_ALQUILER

END 
GO


CREATE PROCEDURE DATABASERS.MIGRAR_BI_BARRIO
AS
BEGIN
	INSERT INTO DATABASERS.BI_BARRIO
	SELECT DISTINCT BARRIO_CODIGO,BARRIO_DETALLE,BARRIO_LOCALIDAD FROM DATABASERS.BARRIO
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_TIPO_INMUEBLE 
AS
BEGIN
	INSERT INTO DATABASERS.BI_TIPO_INMUEBLE
	SELECT DISTINCT TIPO_INMUEBLE_CODIGO, TIPO_INMUEBLE_DETALLE FROM DATABASERS.TIPO_INMUEBLE
END
GO

CREATE PROCEDURE DATABASERS.MIGRAR_BI_LOCALIDAD
AS
BEGIN
	INSERT INTO DATABASERS.BI_LOCALIDAD
	SELECT DISTINCT LOCALIDAD_CODIGO, LOCALIDAD_DETALLE FROM DATABASERS.LOCALIDAD
END
GO


CREATE PROCEDURE DATABASERS.GENERAR_BI_TIEMPO(@fecha datetime, @PK NUMERIC(18,0) OUTPUT)
AS 
BEGIN

	INSERT INTO DATABASERS.BI_TIEMPO 
	(BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE, BI_TIEMPO_MES, BI_TIEMPO_DIA)
	VALUES (YEAR(@FECHA), DATEPART(QUARTER, @FECHA), MONTH(@FECHA), DAY(@FECHA))

	SET @PK = SCOPE_IDENTITY()

END

CREATE PROCEDURE DATABASERS.MIGRAR_BI_TIEMPO_Y_VENTA
AS
BEGIN
	

	DECLARE @VENTA_CODIGO NUMERIC(18)
	DECLARE @VENTA_ANUNCIO NUMERIC(19)
	DECLARE @VENTA_PRECIO_VENTA NUMERIC(18,2)
	DECLARE @VENTA_FECHA DATETIME

	declare c1 cursor for select VENTA_CODIGO, VENTA_ANUNCIO, VENTA_PRECIO_VENTA, VENTA_FECHA from DATABASERS.VENTA
	open c1
	fetch next from c1 into @VENTA_CODIGO, @VENTA_ANUNCIO,@VENTA_PRECIO_VENTA,@VENTA_FECHA
	while @@FETCH_STATUS = 0
	begin 
			
			DECLARE @FK_BI_TIEMPO NUMERIC(18,0)

			SET @FK_BI_TIEMPO = 0 

			EXEC DATABASERS.GENERAR_BI_TIEMPO @FECHA=@VENTA_FECHA, @PK=@FK_BI_TIEMPO OUTPUT

			INSERT INTO DATABASERS.BI_VENTA
			(BI_VENTA_CODIGO,
			BI_VENTA_INMUEBLE_SUPERFICIE_TOTAL,
			BI_VENTA_LOCALIDAD,
			BI_VENTA_PRECIO_VENTA,
			BI_VENTA_TIPO_INMUEBLE,
			BI_VENTA_PRECIO_M2,
			BI_VENTA_TIEMPO)
			SELECT 
			@VENTA_CODIGO,
			(SELECT INMUEBLE_SUPERFICIETOTAL FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON INMUEBLE_CODIGO = ANUNCIO_INMUEBLE
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			(SELECT SUCURSAL_LOCALIDAD FROM DATABASERS.SUCURSAL
			JOIN DATABASERS.ANUNCIO ON ANUNCIO_SUCURSAL = SUCURSAL_CODIGO
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@VENTA_PRECIO_VENTA,
			(SELECT INMUEBLE_TIPO_INMUEBLE FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON ANUNCIO_INMUEBLE = INMUEBLE_CODIGO
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@VENTA_PRECIO_VENTA /(SELECT INMUEBLE_SUPERFICIETOTAL FROM DATABASERS.INMUEBLE
			JOIN DATABASERS.ANUNCIO ON INMUEBLE_CODIGO = ANUNCIO_INMUEBLE
			WHERE ANUNCIO_CODIGO = @VENTA_ANUNCIO),
			@FK_BI_TIEMPO

		fetch next from c1 into @VENTA_CODIGO, @VENTA_ANUNCIO,@VENTA_PRECIO_VENTA,@VENTA_FECHA
	end
	close c1
	deallocate c1



END
GO


CREATE PROCEDURE DATABASERS.MIGRAR_BI_TIEMPO_Y_ALQUILER
AS
BEGIN
	

	DECLARE @ALQUILER_CODIGO NUMERIC(18)
	DECLARE @ALQUILER_FECHA DATETIME

	declare c1 cursor for select ALQUILER_CODIGO, PAGO_ALQUILER_FECHA from DATABASERS.ALQUILER JOIN DATABASERS.PAGO_ALQUILER ON ALQUILER_CODIGO=PAGO_ALQUILER_ALQUILER
	open c1
	fetch next from c1 into @ALQUILER_CODIGO, @ALQUILER_ANUNCIO,@ALQUILER_FECHA
	while @@FETCH_STATUS = 0
	begin 
			
			DECLARE @FK_BI_TIEMPO NUMERIC(18,0)

			SET @FK_BI_TIEMPO = 0 

			EXEC DATABASERS.GENERAR_BI_TIEMPO @FECHA=@ALQUILER_FECHA, @PK=@FK_BI_TIEMPO OUTPUT

			INSERT INTO DATABASERS.BI_ALQUILER
			(BI_ALQUILER_CODIGO,
			BI_ALQUILER_ESTADO,
			BI_ALQUILER_BARRIO,
			BI_ALQUILER_PAGO;
			BI_ALQUILER_ATRASO_PAGO,
			BI_ALQUILER_TIEMPO
			)
			SELECT 
			@ALQUILER_CODIGO,
			(SELECT ALQUILER_ESTADO FROM DATABASERS.ALQUILER
			WHERE ALQUILER_CODIGO = @ALQUILER_CODIGO),
			(SELECT INMUEBLE_BARRIO FROM DATABASERS.ALQUILER JOIN DATABASERS.ANUNCIO ON ALQUILER_ANUNCIO=ANUNCIO_CODIGO
			JOIN DATABASERS.INMUEBLE ON INMUEBLE_CODIGO=ANUNCIO_INMUEBLE),
			(SELECT PAGO_ALQUILER_IMPORTE FROM DATABASERS.ALQUILER 
			JOIN DATABASERS.PAGO_ALQUILER ON PAGO_ALQUILER_ALQUILER=ALQUILER_CODIGO
			WHERE ALQUILER_CODIGO=@ALQUILER_CODIGO),
			(SELECT DATEDIFF(DAY,PAGO_ALQUILER_FECHA_VENCIMIENTO,PAGO_ALQUILER_FECHA) FROM DATABASERS.ALQUILER 
			JOIN DATABASERS.PAGO_ALQUILER ON PAGO_ALQUILER_ALQUILER=ALQUILER_CODIGO
			WHERE ALQUILER_CODIGO=@ALQUILER_CODIGO),
			@FK_BI_TIEMPO

		fetch next from c1 into @ALQUILER_CODIGO,@ALQUILER_FECHA
	end
	close c1
	deallocate c1



END
GO


--VISTAS

CREATE VIEW DATABASERS.PRECIO_PROM_M2_VENTAS
AS
SELECT BI_TIPO_INMUEBLE_DETALLE, BI_LOCALIDAD_DETALLE, BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE, AVG(BI_VENTA_PRECIO_M2) AS PROM_PRECIO_M2
FROM DATABASERS.BI_VENTA 
JOIN DATABASERS.BI_TIPO_INMUEBLE ON BI_VENTA_TIPO_INMUEBLE= BI_TIPO_INMUEBLE_CODIGO
JOIN DATABASERS.BI_LOCALIDAD ON BI_VENTA_LOCALIDAD = BI_LOCALIDAD_CODIGO
JOIN DATABASERS.BI_TIEMPO ON BI_VENTA_TIEMPO = BI_TIEMPO_CODIGO
GROUP BY  BI_TIPO_INMUEBLE_DETALLE, BI_LOCALIDAD_DETALLE, BI_TIEMPO_ANIO, BI_TIEMPO_CUATRIMESTRE

CREATE VIEW DATABASERS.PORCENTAJE_INCUMPLIMIENTO
AS
SELECT (100*(SELECT COUNT(DISTINCT P2.PAGO_ALQUILER_CODIGO) FROM DATABASERS.BI_ALQUILER A2
JOIN DATABASERS.BI_PAGO_ALQUILER P2 ON P2.BI_PAGO_ALQUILER_ALQUILER=A2.BI_ALQUILER_CODIGO
JOIN DATABASERS.BI_TIEMPO T2 ON T2.BI_TIEMPO_CODIGO=A2.ALQUILER_TIEMPO
WHERE P2.PAGO_ALQUILER_FECHA_VENCIMIENTO>P2.PAGO_ALQUILER_FECHA and T2.BI_TIEMPO_ANIO=T1.BI_TIEMPO_ANIO and T2.BI_TIEMPO_MES=T1.BI_TIEMPO_MES
GROUP BY T2.BI_TIEMPO_ANIO,T2.BI_TIEMPO_MES))/COUNT(P1.PAGO_ALQUILER_CODIGO) FROM DATABASERS.BI_ALQUILER A1
JOIN DATABASERS.BI_PAGO_ALQUILER P1 ON A1.BI_ALQUILER_CODIGO=P1.BI_PAGO_ALQUILER_ALQUILER 
JOIN DATABASERS.BI_TIEMPO T1 ON T1.BI_TIEMPO_CODIGO=A1.BI_ALQUILER_TIEMPO
GROUP BY T1.BI_TIEMPO_ANIO,T1.BI_TIEMPO_MES

CREATE VIEW DATABASERS.INCREMENTO_ALQUILER
AS
SELECT (100*(P1.BI_PAGO_ALQUILER_IMPORTE-(SELECT P2.BI_PAGO_ALQUILER_IMPORTE FROM DATABASERS.BI_ALQUILER A2
JOIN DATABASERS.BI_PAGO_ALQUILER P2 ON P2.BI_PAGO_ALQUILER_ALQUILER=A2.BI_ALQUILER_CODIGO 
JOIN DATABASERS.BI_TIEMPO T2 ON T2.BI_TIEMPO_CODIGO=A2.ALQUILER_TIEMPO
WHERE T2.BI_TIEMPO_MES=T1.BI_TIEMPO_MES-1)))/(SELECT P2.BI_PAGO_ALQUILER_IMPORTE FROM DATABASERS.BI_ALQUILER A2
JOIN DATABASERS.BI_PAGO_ALQUILER P2 ON P2.BI_PAGO_ALQUILER_ALQUILER=A2.BI_ALQUILER_CODIGO 
JOIN DATABASERS.BI_TIEMPO T2 ON T2.BI_TIEMPO_CODIGO=A2.ALQUILER_TIEMPO
WHERE T2.BI_TIEMPO_MES=T1.BI_TIEMPO_MES-1) FROM DATABASERS.BI_ALQUILER A1 JOIN DATABASERS.BI_ESTADO_ALQUILER E1 ON E1.BI_ESTADO_ALQUILER_CODIGO=A1.BI_ALQUILER_ESTADO 
JOIN DATABASERS.BI_PAGO_ALQUILER P1 ON P1.BI_PAGO_ALQUILER_ALQUILER=A1.BI_ALQUILER_CODIGO
JOIN DATABASERS.BI_TIEMPO T1 ON T1.BI_TIEMPO_CODIGO=A1.BI_ALQUILER_TIEMPO
WHERE P1.BI_PAGO_ALQUILER_IMPORTE> (SELECT P3.BI_PAGO_ALQUILER_IMPORTE FROM DATABASERS.BI_ALQUILER A3
JOIN DATABASERS.BI_PAGO_ALQUILER P3 ON P3.BI_PAGO_ALQUILER_ALQUILER=A3.BI_ALQUILER_CODIGO 
JOIN DATABASERS.BI_TIEMPO T3 ON T3.BI_TIEMPO_CODIGO=A3.ALQUILER_TIEMPO
WHERE T3.BI_TIEMPO_MES=T1.BI_TIEMPO_MES-1)
GROUP BY T1.BI_TIEMPO_MES
--SELECCION VISTA

SELECT * FROM  DATABASERS.PRECIO_PROM_M2_VENTAS